第8回

In [1]:
import numpy as np

In [2]:
np.arange(0, 5, 2) # start, stop, step

array([0, 2, 4])

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [5]:
np.linspace(1, 2, 20) # 1-2で２０分割

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [6]:
ndarray = np.arange(5)
ndarray_copy = ndarray.copy()

In [7]:
print('original', ndarray)
print('copy', ndarray_copy)

original [0 1 2 3 4]
copy [0 1 2 3 4]


In [8]:
shape = (2, 3, 5)
zeros = np.zeros(shape)
zeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
shape = (2, 3, 5)
ones = np.ones(shape)
ones

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.eye(3, 5) # N*M　殆ど使わん

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [14]:
print(np.random.rand())
print(np.random.rand(3))
print(np.random.rand(3, 4)) # npはライブラリなのでpython的扱い、その中にrandomモジュール入ってる？

0.15222520367027725
[0.93225179 0.37485537 0.24692188]
[[0.6417462  0.81071625 0.91533608 0.99985809]
 [0.88309948 0.73133538 0.63640054 0.78677283]
 [0.42879149 0.11302644 0.41172708 0.35982214]]


In [15]:
np.random.randn(3, 4) # 標準正規分布からランダム

array([[ 1.01031795,  2.30548387,  0.14203783,  1.07419362],
       [-0.10138416,  0.85635201,  1.24659117, -0.51520503],
       [-0.31259577,  2.61559984,  0.58705544, -1.42447164]])

In [16]:
np.random.randint(10, 50, size=(2, 4, 3)) # 10以上５０未満の整数の乱数をsizeで生成

array([[[38, 21, 45],
        [31, 35, 32],
        [10, 28, 40],
        [48, 37, 47]],

       [[19, 41, 27],
        [26, 26, 10],
        [26, 14, 33],
        [34, 22, 23]]])

In [17]:
# 上記、データサイエンス頻出！

In [19]:
# 以下、超超超頻出 reshapeで任意のshapeに変換 要素数がnew_shapeとあってなければエラー
print(np.arange(0, 10))
new_shape = (2, 5)
print('reshaped array\n', np.arange(0, 10).reshape(new_shape))

[0 1 2 3 4 5 6 7 8 9]
reshaped array
 [[0 1 2 3 4]
 [5 6 7 8 9]]
